export enum ErrorCodeEnum {
    /**
     * General errors
     */
    REQUIREMENT_ERROR = 2000,
    AUTHORIZATION_ERROR = 2001,
    FILE_EXTENSION_ERROR = 2002,
    SYSTEM_ERROR = 2003,

    /**
     * Joi validation errors
     */
    VALIDATION_FAIL_TO_MATCH_ERROR = 5006,
    VALIDATION_MATCH_EMPTY_ERROR = 5005,

    /**
     * Client errors
     */
    NOT_FOUND = 404,
    CONFIRMATION_CODE_EXPIRED = 1000,
    CONFIRMATION_CODE_INVALID = 1001,
    CONFIRMATION_VALIDATE_ATTEMPT_EXCEEDED = 1002,
    CONFIRMATION_RESEND_TIMEOUT = 1003,
    CLIENT_ALREADY_EXISTS_ERROR = 1004,
    INVALID_TOKEN_ERROR = 1005,
    CLIENT_IS_NOT_ACTIVE = 1006,
    TOKEN_EXPIRED_ERROR = 1007,
    TOKEN_NOT_PROVIDED_ERROR = 1008,
    INCORRECT_PASSWORD_ERROR = 1009,
    GUEST_CANNOT_CREATE_ERROR = 1010,
    LIMIT_EXCEEDED_ERROR = 1011,
    FILE_SIZE_LARGE_ERROR = 1012,
    ACTIVE_PRODUCT_VARIANT_IS_REQUIRED_ERROR = 1013,
    DELETE_MAIN_PRODUCT_VARIANT_ERROR = 1014,
    /**
     *  Process errors
     */
    PROCESS_IS_PENDING_ERROR = 1200,
}
